Update pdf-tools using vedang/pdf-tools fork
https://github.com/vedang/pdf-tools

This version does not yet appear to be published on Melpa, but seems
to be working better than the old code.  No doubt this will be more
directly installable in future.

Also includes revised dependency tablist 1.0 (updated from 0.70).

diff --git a/elpa/pdf-tools-0.90/build/server/autobuild b/elpa/pdf-tools-0.90/build/server/autobuild
--- a/elpa/pdf-tools-0.90/build/server/autobuild
+++ b/elpa/pdf-tools-0.90/build/server/autobuild
@@ -6,7 +6,7 @@
 
 # Don't exit if some command fails.
 set +e
-# Disalbe file globbing.
+# Disable file globbing.
 set -f
 
 # Boolean variables are true if non-empty and false otherwise.
@@ -30,6 +30,8 @@ DRY_RUN=
 INSTALL_DIR=
 # Whether we can install packages.
 OS_IS_HANDLED=true
+# Which OSs installer to use
+OS=
 
 ## +-----------------------------------------------------------+
 ## * Utility Functions
@@ -38,17 +40,19 @@ OS_IS_HANDLED=true
 usage()
 {
     cat <<EOF
-usage:$(basename "$0") [--help|-n|[-i DIR|-I]]
+usage:$(basename "$0") [--help|-n|-i DIR|[-d -D]|[--os OS]]
 
-    -n      Don't do anything, but check if this OS is handled.
+    -n       Don't do anything, but check if this OS is handled.
 
-    -i DIR  Install the program in the given directory.
+    -i DIR   Install the program in the given directory.
 
-    -d      Force dependency installattion.
+    -d       Force dependency installattion.
 
-    -D      Skip dependency installattion.
+    -D       Skip dependency installattion.
 
-    --help  Display this message.
+    --os OS  Use the given OS's installer
+
+    --help   Display this message.
 
 EOF
     exit "$1"
@@ -163,9 +167,7 @@ have_packages_installed()
         which make || return 1
         which gcc || which cc || return 1
         which g++ || which c++ || return 1
-        cc $(pkg-config --cflags poppler) -o /dev/null -E - 2>/dev/null <<EOF
-        #include <PDFDocEncoding.h>
-EOF
+        c++ $(pkg-config --cflags poppler) -o /dev/null -E install_test.cpp 2>/dev/null
         [ $? -eq 0 ] || return 1
         return 0
     } >/dev/null 2>&1
@@ -185,6 +187,11 @@ handle_options()
                 if [ "${1%%/}" != "${PWD%%/}" ]; then
                     INSTALL_DIR=$1
                 fi ;;
+            --os)
+                shift
+                [ $# -gt 0 ] || usage 1
+                OS="$1"
+                ;;
             *) usage 1 ;;
         esac
         shift
@@ -308,7 +315,7 @@ os_debian() {
               make
               pkg-config"
     PKGCMD=apt-get
-    PKGARGS=install
+    PKGARGS="install -y"
     return 0
 }
 
@@ -355,11 +362,21 @@ os_msys2() {
 os_macos() {
     if ! which uname >/dev/null 2>&1 || [ "$(uname -s)" != "Darwin" ]; then
         return 1
+    elif which brew >/dev/null 2>&1; then
+        PKGCMD=brew
+        PKGARGS=install
+        PACKAGES="pkg-config poppler automake"
+        PKG_INSTALL_AS_ROOT=
+        # homebrew install libffi as keg-only, meaning we need to set
+        # PKG_CONFIG_PATH manually so configure can find it
+        export PKG_CONFIG_PATH="$(brew --prefix libffi)/lib/pkgconfig/"
+    elif which port >/dev/null 2>&1; then
+        PKGCMD=port
+        PKGARGS=install
+        PACKAGES="pkgconfig poppler automake libpng"
+    else
+        return 1
     fi
-    PKGCMD=brew
-    PKGARGS=install
-    PACKAGES="pkg-config poppler automake"
-    PKG_INSTALL_AS_ROOT=
     return 0
 }
 
@@ -400,22 +417,45 @@ os_gentoo() {
     return 0
 }
 
+# By Parameter --os
+os_argument() {
+    [ -z "$OS" ] && return 1
+    case $OS in
+        macos)   os_macos   "$@";;
+        freebsd) os_freebsd "$@";;
+        arch)    os_arch    "$@";;
+        centos)  os_centos  "$@";;
+        openbsd) os_openbsd "$@";;
+        fedora)  os_fedora  "$@";;
+        debian)  os_debian  "$@";;
+        gentoo)  os_gentoo  "$@";;
+        msys2)   os_msys2   "$@";;
+        nixos)   os_nixos   "$@";;
+        *)       echo "Invalid --os argument: $OS"
+                 exit 1
+    esac || {
+        echo "Unable to install on this system as $OS"
+        exit 1
+    }
+}
+
 ## +-----------------------------------------------------------+
 ## * Figure out were we are, install deps and build the program
 ## +-----------------------------------------------------------+
 
 handle_options "$@"
 
-os_macos   "$@" || \
-os_freebsd "$@" || \
-os_arch    "$@" || \
-os_centos  "$@" || \
-os_openbsd "$@" || \
-os_fedora  "$@" || \
-os_debian  "$@" || \
-os_gentoo  "$@" || \
-os_msys2   "$@" || \
-os_nixos   "$@" || \
+os_argument "$@" || \
+os_macos    "$@" || \
+os_freebsd  "$@" || \
+os_arch     "$@" || \
+os_centos   "$@" || \
+os_openbsd  "$@" || \
+os_fedora   "$@" || \
+os_debian   "$@" || \
+os_gentoo   "$@" || \
+os_msys2    "$@" || \
+os_nixos    "$@" || \
 {
     OS_IS_HANDLED=
     if [ -z "$DRY_RUN" ]; then
@@ -448,10 +488,6 @@ if [ -n "$PKGCMD" ];then
     echo
 fi
 
-echo "---------------------------"
-echo " Configuring and compiling "
-echo "---------------------------"
-
 # Try to be in the correct directory.
 if which dirname >/dev/null 2>&1; then
     cd "$(dirname "$0")" || {
@@ -459,6 +495,10 @@ if which dirname >/dev/null 2>&1; then
         exit 1
     }
 fi
+
+echo "---------------------------"
+echo " Configuring and compiling "
+echo "---------------------------"
 
 # Create the configure script.
 if ! [ -f ./configure ]; then
@@ -473,8 +513,8 @@ if [ -n "$INSTALL_DIR" ]; then
     prefix=--bindir=$INSTALL_DIR
 fi
 
-echo "./configure -q $prefix && make -s"
-eval "./configure -q $(quote "$prefix") && make -s || exit_fail"
+echo "./configure -q $prefix && make clean && make -s"
+eval "./configure -q $(quote "$prefix") && make clean && make -s || exit_fail"
 echo
 if [ -n "$INSTALL_DIR" ]; then
     echo "---------------------------"
